/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Complaint_management;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.awt.Graphics;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author HP
 */
public class admnhom extends javax.swing.JFrame 

{    /**
     * Creates new form admnhom
     */
    public admnhom() 
    {
        initComponents();
        Dimension scrsiz=Toolkit.getDefaultToolkit().getScreenSize();
        setSize(scrsiz);
        setResizable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        ImageIcon img=new ImageIcon(getClass().getResource("/images/bg.jpg"));
        Image img1=img.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane()
        {
            public void paintComponent(Graphics g)
            {
                g.drawImage(img1, 0, 0, getWidth(), getHeight(), this);
            }
        }
        ;
        jMenuBar2 = new javax.swing.JMenuBar();
        Menumanage = new javax.swing.JMenu();
        itemaccounts = new javax.swing.JMenuItem();
        Itememployees = new javax.swing.JMenuItem();
        Itemexit = new javax.swing.JMenuItem();
        Menucomplaints = new javax.swing.JMenu();
        Itemregister = new javax.swing.JMenuItem();
        Itemfeedback = new javax.swing.JMenuItem();
        Menureports = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        jMenuItem9.setText("jMenuItem9");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem8.setText("jMenuItem8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COMPLAINT MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        Menumanage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Menumanage.setText("Manage");
        Menumanage.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        Menumanage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenumanageActionPerformed(evt);
            }
        });

        itemaccounts.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        itemaccounts.setText("Accounts");
        itemaccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemaccountsActionPerformed(evt);
            }
        });
        Menumanage.add(itemaccounts);

        Itememployees.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        Itememployees.setText("Employees");
        Itememployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItememployeesActionPerformed(evt);
            }
        });
        Menumanage.add(Itememployees);

        Itemexit.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        Itemexit.setText("Exit");
        Itemexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemexitActionPerformed(evt);
            }
        });
        Menumanage.add(Itemexit);

        jMenuBar2.add(Menumanage);

        Menucomplaints.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Menucomplaints.setText("Complaints");
        Menucomplaints.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N

        Itemregister.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        Itemregister.setText("Register Complaints");
        Itemregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemregisterActionPerformed(evt);
            }
        });
        Menucomplaints.add(Itemregister);

        Itemfeedback.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        Itemfeedback.setText("Complaint feedback");
        Itemfeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemfeedbackActionPerformed(evt);
            }
        });
        Menucomplaints.add(Itemfeedback);

        jMenuBar2.add(Menucomplaints);

        Menureports.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Menureports.setText("Reports");
        Menureports.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N

        jCheckBoxMenuItem1.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Complaints between two dates");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        Menureports.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Complaint handled by an employee");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        Menureports.add(jCheckBoxMenuItem2);

        jCheckBoxMenuItem3.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("Employee's feedback");
        jCheckBoxMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem3ActionPerformed(evt);
            }
        });
        Menureports.add(jCheckBoxMenuItem3);

        jMenuBar2.add(Menureports);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    frmact objact;
    private void itemaccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemaccountsActionPerformed
       if(objact==null || objact.isClosed()==true)
       {
           try {
               objact=new frmact();
           } catch (IOException ex) {
               Logger.getLogger(admnhom.class.getName()).log(Level.SEVERE, null, ex);
           } catch (ClassNotFoundException ex) {
               Logger.getLogger(admnhom.class.getName()).log(Level.SEVERE, null, ex);
           } catch (SQLException ex) {
               Logger.getLogger(admnhom.class.getName()).log(Level.SEVERE, null, ex);
           }
           jDesktopPane1.add(objact);
           objact.setVisible(true);
       }
       else
       {
           objact.setVisible(true);
       }
    }//GEN-LAST:event_itemaccountsActionPerformed

    private void MenumanageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenumanageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenumanageActionPerformed

    private void ItemexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemexitActionPerformed
       System.exit(1);
    }//GEN-LAST:event_ItemexitActionPerformed
    frmemp objemp;
    private void ItememployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItememployeesActionPerformed
       if(objemp==null||objemp.isClosed())
       {
           try {
               objemp=new frmemp();
               jDesktopPane1.add(objemp);
               objemp.setVisible(true);
           } catch (IOException ex) {
               Logger.getLogger(admnhom.class.getName()).log(Level.SEVERE, null, ex);
           } catch (ClassNotFoundException ex) {
               Logger.getLogger(admnhom.class.getName()).log(Level.SEVERE, null, ex);
           } catch (SQLException ex) {
               Logger.getLogger(admnhom.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
       else
       {
           objemp.setVisible(true);
       }
    }//GEN-LAST:event_ItememployeesActionPerformed
    frmcmp objcmp;
    private void ItemregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemregisterActionPerformed
       if(objcmp==null||objcmp.isClosed())
       {
           objcmp=new frmcmp();
           jDesktopPane1.add(objcmp);
           objcmp.setVisible(true);
       }
    }//GEN-LAST:event_ItemregisterActionPerformed
     frmvst objvst;
    private void ItemfeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemfeedbackActionPerformed
        if(objvst==null||objvst.isClosed())
        {
            objvst=new frmvst();
            jDesktopPane1.add(objvst);
            objvst.setVisible(true);
        }
        else
            objvst.setVisible(true);
    }//GEN-LAST:event_ItemfeedbackActionPerformed
frmempprfrep objrep;
    private void jCheckBoxMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem3ActionPerformed
        // TODO add your handling code here:
         if(objrep==null||objrep.isClosed())
        {
            objrep=new frmempprfrep();
            jDesktopPane1.add(objrep);
            objrep.setVisible(true);
        }
        else
            objrep.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem3ActionPerformed
frmcmpbyemp objcmpemp;
    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
        // TODO add your handling code here:
         if(objcmpemp==null||objcmpemp.isClosed())
        {
             try {
                 objcmpemp=new frmcmpbyemp();
                 jDesktopPane1.add(objcmpemp);
                 objcmpemp.setVisible(true);
             } catch (IOException ex) {
                 Logger.getLogger(admnhom.class.getName()).log(Level.SEVERE, null, ex);
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(admnhom.class.getName()).log(Level.SEVERE, null, ex);
             } catch (SQLException ex) {
                 Logger.getLogger(admnhom.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
        else
            objcmpemp.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed
    frmcrtmonthrep objmonth;
    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        if(objmonth==null||objmonth.isClosed())
        {
            try {
                objmonth=new frmcrtmonthrep();
                jDesktopPane1.add(objmonth);
                objmonth.setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(admnhom.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(admnhom.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
            objmonth.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admnhom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admnhom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admnhom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admnhom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admnhom().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Itememployees;
    private javax.swing.JMenuItem Itemexit;
    private javax.swing.JMenuItem Itemfeedback;
    private javax.swing.JMenuItem Itemregister;
    private javax.swing.JMenu Menucomplaints;
    private javax.swing.JMenu Menumanage;
    private javax.swing.JMenu Menureports;
    private javax.swing.JMenuItem itemaccounts;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables

}


