/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Complaint_management;

import java.awt.Component;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author HP
 */
public class frmemp extends javax.swing.JInternalFrame {
    /**
     * Creates new form frmemp
     */
    public frmemp() throws IOException, ClassNotFoundException, SQLException {
        initComponents();
        setClosable(true);
        setLocation(400,100);
        loaddata();
       DefaultTableColumnModel mod=(DefaultTableColumnModel)jTable2.getColumnModel();
        TableColumn col=mod.getColumn(4);
       col.setCellRenderer(new TableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable jtable, Object o, boolean bln, boolean bln1, int i, int i1) {
               JLabel lbl=new JLabel();
               //ImageIcon imageIcon = new ImageIcon(new ImageIcon(o).getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
               lbl.setIcon((ImageIcon)o);
               lbl.setSize(50,50);
               return lbl;
            }
        });
 jTable2.setRowHeight(80);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtphnno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboloc = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtpicture = new javax.swing.JTextField();
        picturebutton = new javax.swing.JButton();
        savebutton = new javax.swing.JButton();
        updatebutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        cancelbutton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 0)));
        setTitle("Employees");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 0)));
        jPanel1.setForeground(new java.awt.Color(0, 153, 0));
        jPanel1.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Employee Name");

        txtname.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        txtname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("Contact Number");

        txtphnno.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        txtphnno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setText("Select Location");

        comboloc.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        comboloc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chandigarh", "Mohali", "Panchkula", "Patiala", " " }));
        comboloc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("Browse Picture");

        txtpicture.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        txtpicture.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtpicture.setEnabled(false);
        txtpicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpictureActionPerformed(evt);
            }
        });

        picturebutton.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        picturebutton.setForeground(new java.awt.Color(0, 153, 0));
        picturebutton.setText("...");
        picturebutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        picturebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                picturebuttonActionPerformed(evt);
            }
        });

        savebutton.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        savebutton.setForeground(new java.awt.Color(0, 153, 0));
        savebutton.setText("Save");
        savebutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });

        updatebutton.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        updatebutton.setForeground(new java.awt.Color(0, 153, 0));
        updatebutton.setText("Update");
        updatebutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });

        deletebutton.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        deletebutton.setForeground(new java.awt.Color(0, 153, 0));
        deletebutton.setText("Delete");
        deletebutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });

        cancelbutton.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        cancelbutton.setForeground(new java.awt.Color(0, 153, 0));
        cancelbutton.setText("Cancel");
        cancelbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbuttonActionPerformed(evt);
            }
        });

        jTable2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 0)));
        jTable2.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee code", "Employee Name", "Contact Number", "Location", "Picture"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtname)
                            .addComponent(txtphnno)
                            .addComponent(comboloc, 0, 234, Short.MAX_VALUE)
                            .addComponent(txtpicture))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(picturebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(savebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(updatebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(deletebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(cancelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtphnno, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboloc))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtpicture)
                        .addComponent(picturebutton)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savebutton)
                    .addComponent(deletebutton)
                    .addComponent(cancelbutton)
                    .addComponent(updatebutton))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        try {
            clsemp obj=new clsemp();
            clsempprp objprp=new clsempprp();
            objprp.setEmpno(eno);
            obj.delemp(objprp);
            clear();
            loaddata();
        } catch (IOException ex) {
            Logger.getLogger(frmact.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmact.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frmact.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
        if(txtname.getText().equals("")||txtphnno.getText().equals("")||txtpicture.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please fill entries");
        }
        else
        {
                clsempprp objprp=new clsempprp();
                clsemp obj=new clsemp();
                objprp.setEmpnam(txtname.getText());
                objprp.setEmpphnno(txtphnno.getText());
                objprp.setEmploc(comboloc.getSelectedItem().toString());
                String s=txtpicture.getText();
                s=s.substring(s.lastIndexOf("\\")+1);
                objprp.setEmppic(s);
               try {
                obj.insemp(objprp);
                saveimage();
                loaddata();
                clear();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(frmact.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(frmact.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(frmact.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_savebuttonActionPerformed
int eno;
    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
              if(txtname.getText().equals((""))||txtphnno.getText().equals("")||txtpicture.getText().equals(""))
       {
           JOptionPane.showMessageDialog(this, "Please fill entries");
       }
       else
       {
                  try {
                      clsempprp objprp=new clsempprp();
                      clsemp obj=new clsemp();
                      objprp.setEmpnam(txtname.getText());
                      objprp.setEmploc(comboloc.getSelectedItem().toString());
                      objprp.setEmpphnno(txtphnno.getText());
                      String s=txtpicture.getText();
                      if(s.equals("")==true)
                      {
                          try {
                              clsempprp k = obj.fndemp(eno);
                              objprp.setEmppic(k.getEmppic());
                          } catch (IOException ex) {
                              Logger.getLogger(frmemp.class.getName()).log(Level.SEVERE, null, ex);
                          } catch (ClassNotFoundException ex) {
                              Logger.getLogger(frmemp.class.getName()).log(Level.SEVERE, null, ex);
                          } catch (SQLException ex) {
                              Logger.getLogger(frmemp.class.getName()).log(Level.SEVERE, null, ex);
                          }
                      }
                      else
                      {
                          s=s.substring(s.lastIndexOf("\\")+1);
                          objprp.setEmppic(s);
                      }
                      objprp.setEmpno(eno);
                      obj.updemp(objprp);

                      saveimage();
                      loaddata();
                      clear();
                  } catch (IOException ex) {
                      Logger.getLogger(frmemp.class.getName()).log(Level.SEVERE, null, ex);
                  } catch (ClassNotFoundException ex) {
                      Logger.getLogger(frmemp.class.getName()).log(Level.SEVERE, null, ex);
                  } catch (SQLException ex) {
                      Logger.getLogger(frmemp.class.getName()).log(Level.SEVERE, null, ex);
                  }
           }
 
    }//GEN-LAST:event_updatebuttonActionPerformed

    private void picturebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_picturebuttonActionPerformed
        JFileChooser jf=new JFileChooser();
        jf.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int a=jf.showOpenDialog(this);
        if(a==JFileChooser.APPROVE_OPTION)
          txtpicture.setText(jf.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_picturebuttonActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
       int idx=jTable2.getSelectedRow();
       if(idx!=-1)
       {
          eno=(int)jTable2.getValueAt(idx,0);
    txtname.setText(jTable2.getValueAt(idx,1).toString());
    txtphnno.setText(jTable2.getValueAt(idx,2).toString());
    comboloc.setSelectedItem(jTable2.getValueAt(idx, 3).toString());
    txtpicture.setText(jTable2.getValueAt(idx, 4).toString());
          deletebutton.setEnabled(true);
          updatebutton.setEnabled(true);
       }
    }//GEN-LAST:event_jTable2MouseClicked

    private void txtpictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpictureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpictureActionPerformed

    private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbuttonActionPerformed
        // TODO add your handling code here:
     clear();
    }//GEN-LAST:event_cancelbuttonActionPerformed
private void clear()
    {
        txtname.setText(null);
        txtphnno.setText(null);
        txtpicture.setText(null);
    }
    private void loaddata() throws IOException, ClassNotFoundException, SQLException
    {
        DefaultTableModel mod = (DefaultTableModel)(jTable2.getModel());
        clsemp obj=new clsemp();
        ArrayList <clsempprp> k=obj.dspemp();
        mod.setRowCount(0);
        for(clsempprp p:k)
        {
            Object[] rowdata = new Object[6];
            rowdata[0]=p.getEmpno();
            rowdata[1]=p.getEmpnam();
            rowdata[2]=p.getEmpphnno();
            rowdata[3]=p.getEmploc();
            ImageIcon img=new ImageIcon(getClass().getResource("/emppics/"+p.getEmppic()));
            rowdata[4]=img;
            mod.addRow(rowdata);
        }
        jTable2.setModel(mod);
    }
    public void saveimage()
    {
        String hh=txtpicture.getText();
        if(hh.equals("")==true)
        {
            
        }
        else
        {
            try {
                Path source=Paths.get(txtpicture.getText());
                Path targetDir=Paths.get("D:\\java\\Complaint_management project\\src\\emppics");
                Files.createDirectories(targetDir);
                String s=txtpicture.getText();
                s=s.substring(s.lastIndexOf("\\")+1);
                Path target=targetDir.resolve(s);
                Files.copy(source, target, StandardCopyOption.REPLACE_EXISTING);
            } catch (IOException ex) {
                Logger.getLogger(frmemp.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelbutton;
    private javax.swing.JComboBox<String> comboloc;
    private javax.swing.JButton deletebutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton picturebutton;
    private javax.swing.JButton savebutton;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphnno;
    private javax.swing.JTextField txtpicture;
    private javax.swing.JButton updatebutton;
    // End of variables declaration//GEN-END:variables
}
